from __future__ import annotations

import os


_ENGLISH_REPLACEMENTS = (
    ("Клиенты со средним и высоким риском за 14 дней", "Medium- and high-risk clients in the last 14 days"),
    ("Структура воронки по закреплённым клиентам", "Deal pipeline for assigned clients"),
    ("Три компактных графика по ключевым отклонениям", "Three compact views of the key deviations"),
    ("Сегодня требуют внимания:", "Today needs attention:"),
    ("Клиенты в фокусе", "Clients in focus"),
    ("Высокие риски", "High risks"),
    ("Сделки без КП", "Deals without proposal"),
    ("Задачи по статусам", "Tasks by status"),
    ("Сделки по стадиям", "Deals by stage"),
    ("Ближайшие встречи", "Upcoming meetings"),
    ("Разделы", "Sections"),
    ("Проверки", "Checks"),
    ("Сводка дня", "Daily summary"),
    ("(администратор)", "(administrator)"),
    ("по статусам", "by status"),
    ("по стадиям", "by stage"),
    ("в работе", "in progress"),
    ("просроченные", "overdue"),
    ("просрочены", "overdue"),
    ("выполненные", "completed"),
    ("сегодня", "today"),
    ("Ближайшие", "Upcoming"),
    ("Разобрать", "Review"),
    ("Проверить", "Check"),
    ("Начать", "Start"),
    ("Спросить AI", "Ask AI"),
    ("Поиск клиента", "Search clients"),
    ("Поиск", "Search"),
    ("Выберите клиента в таблице", "Select a client from the table"),
    ("Выберите задачу", "Select a task"),
    ("Выберите встречу", "Select a meeting"),
    ("Основная информация", "Core information"),
    ("Контактное лицо: Не указано", "Contact: not set"),
    ("ИНН: Не указан", "Tax ID: not set"),
    ("Важные даты", "Key dates"),
    ("Описание компании пока не заполнено.", "Company profile has not been completed."),
    ("Описание компании", "Company profile"),
    ("Ключевые показатели", "Key metrics"),
    ("Задачи и риски", "Tasks and risks"),
    ("Команда по клиенту", "Client team"),
    ("Команда: По данным", "Team: no data"),
    ("Сформировать справ", "Generate brief"),
    ("Сформировать PDF", "Generate PDF"),
    ("Есть overdue tasks", "Overdue tasks"),
    ("Health score ниже 60", "Health score below 60"),
    ("срок", "due"),
    ("Не указано", "not set"),
    ("По данным", "no data"),
    ("Нет данных", "No data"),
    ("Детали задачи", "Task details"),
    ("Детали задач", "Task details"),
    ("Создать клиента", "Create client"),
    ("Создать встречу", "Create meeting"),
    ("Следующий", "Next"),
    ("Предыдущий", "Previous"),
    ("Неделя", "Week"),
    ("Накладки", "Overlaps"),
    ("Отрасль", "Industry"),
    ("Сегмент", "Segment"),
    ("Приоритет", "Priority"),
    ("Оценка", "Score"),
    ("Статус", "Status"),
    ("Последний", "Last"),
    ("Проект", "Project"),
    ("Исполнитель", "Assignee"),
    ("Срок", "Due"),
    ("высокий", "high"),
    ("средний", "medium"),
    ("просрочена", "overdue"),
    ("просрочен", "overdue"),
    ("Администратор системы", "System Administrator"),
    ("Демо компания", "Demo Company"),
    ("Добрый день", "Good afternoon"),
    ("Требуется внимание", "Needs attention"),
    ("Клиентов", "Clients"),
    ("Клиенты", "Clients"),
    ("клиентов", "clients"),
    ("Клиент", "Client"),
    ("клиент", "client"),
    ("Сделки", "Deals"),
    ("сделки", "deals"),
    ("Сделка", "Deal"),
    ("сделка", "deal"),
    ("Задачи", "Tasks"),
    ("задачи", "tasks"),
    ("Задача", "Task"),
    ("задача", "task"),
    ("Встречи", "Meetings"),
    ("встречи", "meetings"),
    ("Встреча", "Meeting"),
    ("встреча", "meeting"),
    ("Панель", "Dashboard"),
    ("Проекты", "Projects"),
    ("проект", "project"),
    ("Календарь", "Calendar"),
    ("Показатели", "Metrics"),
    ("Сообщения", "Messages"),
    ("Уведомления", "Notifications"),
    ("Шаблоны", "Templates"),
    ("Ежедневная сводка", "Daily digest"),
    ("Справка клиента", "Client brief"),
    ("Аналитика портфеля", "Portfolio analytics"),
    ("Динамика рисков", "Risk trend"),
    ("Задачи по статусам", "Tasks by status"),
    ("Сделки по стадиям", "Deals by stage"),
    ("Что требует внимания", "Requires attention"),
    ("Ближайшие встречи", "Upcoming meetings"),
    ("Рекомендации AI", "AI recommendations"),
    ("Подробнее", "View details"),
    ("Открыть", "Open"),
    ("Создать", "Create"),
    ("Сегодня", "Today"),
    ("завтра", "tomorrow"),
    ("просрочка", "overdue"),
    ("Просроченные", "Overdue"),
    ("Просроченные задачи", "Overdue tasks"),
    ("Нет", "No"),
    ("нет", "no"),
    ("Новые", "New"),
    ("Новая", "New"),
    ("В работе", "In progress"),
    ("Выполнены", "Completed"),
    ("активен", "active"),
    ("закрыт", "closed"),
    ("открыта", "open"),
    ("заблокирована", "blocked"),
    ("завершена", "completed"),
    ("запланирована", "planned"),
    ("с задержкой", "delayed"),
    ("высокий риск", "high risk"),
    ("нет встречи", "no meeting"),
    ("нет КП", "no proposal"),
    ("ниже плана", "below plan"),
    ("внимание", "attention"),
    ("Риск", "Risk"),
    ("риски", "risks"),
    ("Риски", "Risks"),
    ("Все", "All"),
    ("Сводка", "Summary"),
    ("Запросить AI", "Ask AI"),
    ("AI-ассистент", "AI assistant"),
    ("Задайте вопрос по клиентам, рискам, задачам или сделкам.", "Ask about clients, risks, tasks or deals."),
    ("Раздел:", "Section:"),
)


def localize(text: object) -> str:
    """Translate display text for the public English-language workspace."""
    value = "" if text is None else str(text)
    if os.getenv("APP_LOCALE", "en").lower() != "en":
        return value
    for source, target in sorted(_ENGLISH_REPLACEMENTS, key=lambda item: len(item[0]), reverse=True):
        value = value.replace(source, target)
    return value
