# Generated by Django 5.2.16 on 2026-07-17 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('VALIDATING', 'Validating'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=16)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_input_path', models.CharField(max_length=1024)),
                ('output_directory', models.CharField(blank=True, max_length=1024)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_stage', models.CharField(blank=True, max_length=120)),
                ('companies_total', models.PositiveIntegerField(default=0)),
                ('companies_processed', models.PositiveIntegerField(default=0)),
                ('auto_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('class_a_count', models.PositiveIntegerField(default=0)),
                ('class_b_count', models.PositiveIntegerField(default=0)),
                ('non_fintech_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('external_network_enabled', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('model_version', models.CharField(blank=True, max_length=256)),
                ('feature_fingerprint', models.CharField(blank=True, max_length=128)),
                ('run_report', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=128)),
                ('canonical_name', models.CharField(blank=True, max_length=512)),
                ('inn', models.CharField(blank=True, max_length=16)),
                ('operation_count', models.PositiveIntegerField(default=0)),
                ('final_class', models.CharField(max_length=32)),
                ('decision_status', models.CharField(max_length=32)),
                ('final_confidence', models.FloatField(default=0)),
                ('probability_a', models.FloatField(default=0)),
                ('probability_b', models.FloatField(default=0)),
                ('probability_non_fintech', models.FloatField(default=0)),
                ('rule_score_a', models.FloatField(default=0)),
                ('rule_score_b', models.FloatField(default=0)),
                ('rule_score_non_fintech', models.FloatField(default=0)),
                ('models_agree', models.BooleanField(default=False)),
                ('site_url', models.CharField(blank=True, max_length=1024)),
                ('site_status', models.CharField(blank=True, max_length=64)),
                ('data_quality_score', models.FloatField(default=0)),
                ('score_gap', models.FloatField(default=0)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('manual_override_class', models.CharField(blank=True, max_length=32, null=True)),
                ('manual_override_comment', models.TextField(blank=True)),
                ('manual_override_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='classifier_ui.classificationrun')),
            ],
            options={
                'ordering': ['-final_confidence', 'canonical_name'],
                'unique_together': {('run', 'company_id')},
            },
        ),
    ]
