# Generated by Django 5.2.16 on 2026-07-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationrun',
            name='external_network_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
